In [1]:
import numpy as np

prices = np.array([100,200,300])
discount = np.array([0.9])
discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [6]:
prices = np.random.randint(100,500, size=(3,3))
discount = np.array([10,20,30])
result = prices + discount
print(prices)
print(result)

[[395 203 329]
 [262 350 367]
 [362 109 410]]
[[405 223 359]
 [272 370 397]
 [372 129 440]]


In [9]:
array = np.array([1,2,3,4,5])
print(np.all(array > 0))

True


In [ ]:
print(np.any(array > 5))


False


In [13]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated = np.concatenate((array_a, array_b))
print(concatenated)

[1 2 3 4 5 6]


In [17]:
stacked_v = np.vstack((array_a, array_b))
print(stacked_v)
stacked_h = np.hstack((array_a, array_b))
print(stacked_h)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [21]:
array_c = np.arange(1,10)
split_array = np.split(array_c,3)
print(split_array)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
