EJERCICIO

In [31]:
import numpy as np


meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])

ventas_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
ventas_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
ventas_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

print("Media de ventas Producto A: ", np.mean(ventas_A))
print("--> Suma de ventas Producto A: ", np.sum(ventas_A))
print("Media de ventas Producto B: ", np.mean(ventas_B))
print("--> Suma de ventas Producto B: ", np.sum(ventas_B))
print("Media de ventas Producto C: ", np.mean(ventas_C))
print("--> Suma de ventas Producto C: ", np.sum(ventas_C))

suma = ventas_A + ventas_B + ventas_C
result = list(zip(meses, suma))
for month, total in result:
    print('[' + str(month) + '] Total: ' + str(total))


Media de ventas Producto A:  229.16666666666666
--> Suma de ventas Producto A:  2750
Media de ventas Producto B:  257.5
--> Suma de ventas Producto B:  3090
Media de ventas Producto C:  310.0
--> Suma de ventas Producto C:  3720
[Enero] Total: 530
[Febrero] Total: 630
[Marzo] Total: 720
[Abril] Total: 810
[Mayo] Total: 770
[Junio] Total: 770
[Julio] Total: 740
[Agosto] Total: 780
[Septiembre] Total: 860
[Octubre] Total: 910
[Noviembre] Total: 990
[Diciembre] Total: 1050


In [ ]:
mes_mayor_venta = meses[np.argmax(suma)]
mes_menor_venta = meses[np.argmin(suma)]
print(f"Mes con mayor ventas: {mes_mayor_venta}")
print(f"Mes con menor ventas: {mes_menor_venta}")

11
Mes con mayor ventas: Diciembre
Mes con menor ventas: Enero


In [ ]:
matriz2D = np.array([ventas_A, ventas_B, ventas_C])
print("Original")
print(matriz2D)
reshape = matriz2D.reshape(3,4,3)
# print("Redimensionado")
# print(reshape)
traspuesto = matriz2D.T
# print("Traspuesto")
# print(traspuesto)
inverso = matriz2D[:, ::-1]
# print(inverso)
aplanado = matriz2D.flatten()
print(aplanado)

In [ ]:
unicos, counts = np.unique(matriz2D, return_counts=True)

for i, data in enumerate(unicos):
    print(f"[{data}: {counts[i]}]")

In [ ]:
primer_trimestre = matriz2D[0:3, 0:3]
print(primer_trimestre)

[[150 200 250]]


In [41]:
suma = ventas_A + ventas_B + ventas_C
result = list(zip(meses, suma))

index_bool = suma > 800
print(suma)
meses_altas_ventas = meses[suma > 800]
print(meses_altas_ventas)

# for index, data in enumerate(result):
#     if(index_bool[index] == True):
#         print(f"[{data[0]}]: {data[1]}")

[ 530  630  720  810  770  770  740  780  860  910  990 1050]
['Abril' 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']


In [47]:
# Selección avanzada
indices = [0, 2, 4, 6, 8, 10]
ventas_indices_seleccionados = matriz2D[:, indices]
print("Ventas en meses seleccionados:\n", ventas_indices_seleccionados)

Ventas en meses seleccionados:
 [[150 250 220 180 230 280]
 [180 230 270 240 270 310]
 [200 240 280 320 360 400]]
