In [24]:
import numpy as np

array = np.array([10,20,30,40,50])
print(array[1])
print(array[-1])

20
50


Aquí nos traemos los datos del array desde la posición 1 hasta la 4 (4 no incluyente)

In [27]:
print(array[0:1])
print(array[-1:-4])

[10]
[]


Aquí estamos ejecutando una indexación booleana, nos devuelve una lista de booleanos que cumplen con la condición.

In [7]:
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


Podemos ver que estamos accediendo a varios index en simultaneo del array

In [9]:
index = [2,0,4]
print(array[index])

[30 10 50]


Ya que tenemos 2 dimensiones al acceder al index lo hacemos mediante dos números, en este caso estamos indicado que queremos acceder a la columna 0 posición 1.

In [28]:
array = np.random.randint(1, 10, size=(3,3))
print(array)
print(array[0,1])


[[8 2 6]
 [1 2 8]
 [2 4 9]]
2


Aquí estamos haciendo un slice de la matriz al indicar dos valores, al no especificar un valor toma como 0. Los valores antes de la coma corresponde a las cordenadas de la fila y los valores después de la coma corresponden a las cordenadas de las columnas.

Por ejemplo array[1:2,2:3] fila [1:2] - columna [2:3]

[1:2] significa: párate en la fila 1 (la segunda, el 0 cuenta) y bajarás antes de la fila 2, es decir no es incluyente. Por lo que solo estamos tomando la columna 1. [2:3] significa toma la columna 2 (el 0 cuenta) y detente antes de la columna 3 (no incluyente) así que estamos tomando la fila 1 y la columna 2. bajo esta idea solo estamos sacando un único valor.

In [52]:
print(array[1:3,1:3])
# print(array[:2,:2])

[[2 8]
 [4 9]]
