Introducción al uso de numpy y los escalares.
numpy es una librería muy amplia para cálculos matemáticos.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

escalar = np.array(42)
print(escalar)
print(type(escalar))

42
<class 'numpy.ndarray'>


In [2]:
vector = np.array([30,29,42,35,31,33,36,42])
print(vector)

[30 29 42 35 31 33 36 42]


In [3]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [6]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
diag = np.diag([1,2,3,4,5,6,7,8,9])
print(diag)

[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]


En la función de abajo vemos como se generan números aleatorios (entre 0 y 1) en una matriz de 2 x 3

In [10]:
random = np.random.random((2,3))
print(random)

[[0.5644825  0.16141656 0.06221511]
 [0.1188061  0.03694919 0.1015342 ]]
