Arrays en Numpy

.ndim -> Para ver las dimensiones.
.shape -> Para ver la medida de cada dimensión.
.dtype -> el datatype de los registros.

In [2]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])
print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int64


Datatype: Es un objeto de numpy que describe el tipo de elementos dentro del array, puede ser entero, flotante o booleano, también el tamaño del dato, ejemplo: 8bits, 16bits, etc.  

uint8 -> Es un entero sin signo de 8bits, puede representar valores entre 0 y 255. útil para trabajar con datos que no pueden ser negativos como colores donde cada color puede tener un valor entre 0 y 255.

float32 -> número de punto flotante de 32bits. Representa valores con decimales y se usan para manejar precisión moderada pero donde se requiere ahorra bits.

float64 -> Lo mismo que el anterior pero de 64bits. Ofrece mayor precisión y es el valor por defecto para decimales que usa numpy.

In [2]:
z = np.array(3, dtype=np.uint8)
print(z)

3


dtype='d' los convierte a número flotante de 64bit por defecto

In [3]:
double_array = np.array([1,2,3], dtype='d')
print(double_array)

[1. 2. 3.]


In [4]:
z = z.astype(np.float64)
print(z)

3.0


Aquí estamos sumando el array que creamos más arriba.

In [5]:
sum = np.sum(array)
print(sum)

21


.mean() para calcular la media.

In [3]:
mean = np.mean(array)
print(mean)

3.5


.sdt() para calcular la desviación estándar.


In [7]:
std = np.std(array)
print(std)

1.707825127659933


Operaciones matemáticas entre matrices:

SUMA DE MATRICES:

In [14]:
A = np.array([[1, 2], [3, 4],])
B = np.array([[5, 6], [7, 8]])

suma = A + B
print("Suma de matrices:\n", suma)

Suma de matrices:
 [[ 6  8]
 [10 12]]


PRODUCTO DE MATRICES

In [9]:
producto = np.dot(A, B)
print("Producto de matrices:\n", producto)

Producto de matrices:
 [[19 22]
 [43 50]]


DETERMINANTE DE UNA MATRIZ (SOLO VALIDO EN UNA MATRIZ CUADRADA)

In [15]:
determinante = np.linalg.det(A)
print("Determinante de A:", determinante)

Determinante de A: -2.0000000000000004


INVERSA DE UNA MATRIZ

In [16]:
inversa = np.linalg.inv(A)
print("Inversa de A:\n", inversa)

Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


Valores y vectores propios

Los valores propios y los vectores propios son fundamentales en muchas aplicaciones, como en la compresión de datos y el análisis de sistemas dinámicos.

In [17]:
valores_propios, vectores_propios = np.linalg.eig(A)
print("Valores propios de A:\n", valores_propios)
print("Vectores propios de A:\n", vectores_propios)

Valores propios de A:
 [-0.37228132  5.37228132]
Vectores propios de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Resolución de sistemas de ecuaciones lineales

Para resolver un sistema de ecuaciones lineales AX=BAX = BAX=B:

In [18]:
B = np.array([1, 2])
X = np.linalg.solve(A, B)
print("Solución del sistema AX = B:\n", X)

Solución del sistema AX = B:
 [0.  0.5]
