Trasponer una matriz.

In [1]:
import numpy as np

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
transposed_matrix = matrix.T
print(matrix)
print(transposed_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Es importante tener en cuenta la dimensionalidad para hacer el reshape. Por ejemplo, abajo tomamos los números del 1 al 12 y los ordenamos en una matriz de 3 x 4, lo cuál cabe perfectamente, pero si nos salimos del rango obtendremos un error.

In [5]:
array = np.arange(1,13)
reshape_array = array.reshape(3,4)
print(array)
print(reshape_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Invertir un array

In [6]:
reversed_array = array[::-1]
print(reversed_array)

[12 11 10  9  8  7  6  5  4  3  2  1]


Aplatar una matriz para volverla unidimensional.

In [8]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flattened_array = matrix.flatten()
print(matrix)
print(flattened_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
