In [2]:
import numpy as np

# Supongamos que tenemos la variable 'respuestas' con las opiniones de los clientes
respuestas = np.array(['bueno', 'excelente', 'malo', 'bueno', 'excelente', 'bueno', 'malo', 'excelente'])

print(np.unique(respuestas))

['bueno' 'excelente' 'malo']


In [3]:
unique_elements, counts = np.unique(respuestas, return_counts = True)
print(unique_elements)
print(counts)

['bueno' 'excelente' 'malo']
[3 3 2]


Importante tener en cuenta que view_y apunta a la misma dirección de memoria que la lista original, así que si la lista original se modifica, también lo hará el view.

In [6]:
array_x = np.arange(10)
view_y = array_x[1:3]
print(array_x)
print(view_y)

array_x[1:3] = [10,11]

print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


Cuando hacemos doble llaves [[]] podemos copiar el array sin apuntar a la misma dirección de memoria

In [11]:
copy_x = array_x[[1,2]]

array_x[1:3] = [14,15]
print(array_x)
print(copy_x)

[ 0 14 15  3  4  5  6  7  8  9]
[12 13]
